# Commodity Code url configuration
COMMODITY_CODES:
  endpoint_url: 'https://www.cbs.nl/-/media/cbsvooruwbedrijf/international-trade-in-goods/commoditycodes-2023.xlsx'
  output_filename: 'CN8 Codes.csv'

# FX rate url configuration
FX_RATES:
  endpoint_url: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml'
  xml_namespaces: {'ex': 'http://www.ecb.int/vocabulary/2002-08-01/eurofxref'}
  xml_child: './/ex:Cube'
  output_filename: 'ECB FX Rates.csv'

# Intrastat specific configuration
INTRASTAT:
  endpoint_url: 'https://github.com/homodudu/Data-Engineering/raw/main/intrastat/_resources/Intrastat%20Data%20Sample.xlsx'
  output_filename: 'Intrastat Submission Sample.xlsx'

# Logging configuration
logging:
  version: 1
  formatters:
    intrastat:
      format: "Intrastat - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: intrastat
      level: DEBUG
    file:
      class: logging.FileHandler
      formatter: intrastat
      filename: intrastat.log
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console,file]
